### PR TITLE
Added links to Cordova, Ionic, PhoneGap and John Papa's Style Guide

### PR DESCRIPTION
**Pull request by bcbeatty**
Added links to Cordova, Ionic, PhoneGap and John Papa's Style Guide

### CODE REVIEW

**Comment by rockfordlhotka** [comment]
If the only thing we're doing is creating reference links for other content, that should go in the Note associated with the video on yammer so people have one place for reference.

If there's _code_ associated, then I'd think that should end up on GitHub/VSTS - with a link to the code from the Note in yammer.

**Comment by bcbeatty** [comment]
This assumes we will be coming from yammer to see this content.
I started on the path because I hadn't heard of John Papa's style guide. So I thought a link to it for others would be helpful.

**Comment by rockfordlhotka** [comment]
Yes, the MMO start point is the MMO group in yammer. I don't want multiple launch points for people to find the videos/information.

**Comment by TrueGeek** [comment]
We do need a place to store links and such and the problem with Yammer is that people outside of Magenic watching these videos don't have access to Yammer.

As a solution can we have Yammer be the internal launch point but GitHub be the repository for both source code and links?

**Comment by rockfordlhotka** [comment]
These videos are intended only for internal Magenic use - we're not creating them for public consumption. So requiring access to yammer should be a non-issue.

Reference materials such as links for the Ionic video should be placed in this note: https://www.yammer.com/magenic.com/#/notes/2829800

**Comment by TrueGeek** [comment]
Ah, okay. Thanks for clearing that up Rocky.

**Pull request closed without merging**
